// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: grpc.proto

package grpc

import (
	reflect "reflect"
	unsafe "unsafe"

	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URLShortenRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	URL           string                 `protobuf:"bytes,1,opt,name=url,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLShortenRequest) Reset() {
	*x = URLShortenRequest{}
	mi := &file_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenRequest) ProtoMessage() {}

func (x *URLShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLShortenRequest) GetUrl() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *URLShortenRequest) SetUrl(v string) {
	x.URL = v
}

type URLShortenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url string
}

func (b0 URLShortenRequest_builder) Build() *URLShortenRequest {
	m0 := &URLShortenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.URL = b.Url
	return m0
}

type URLShortenResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLShortenResponse) Reset() {
	*x = URLShortenResponse{}
	mi := &file_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenResponse) ProtoMessage() {}

func (x *URLShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLShortenResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *URLShortenResponse) SetResult(v string) {
	x.Result = v
}

type URLShortenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result string
}

func (b0 URLShortenResponse_builder) Build() *URLShortenResponse {
	m0 := &URLShortenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Result = b.Result
	return m0
}

type URLExpandRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandRequest) Reset() {
	*x = URLExpandRequest{}
	mi := &file_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandRequest) ProtoMessage() {}

func (x *URLExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLExpandRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *URLExpandRequest) SetID(v string) {
	x.ID = v
}

type URLExpandRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID string
}

func (b0 URLExpandRequest_builder) Build() *URLExpandRequest {
	m0 := &URLExpandRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ID = b.ID
	return m0
}

type URLExpandResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLExpandResponse) Reset() {
	*x = URLExpandResponse{}
	mi := &file_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLExpandResponse) ProtoMessage() {}

func (x *URLExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLExpandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *URLExpandResponse) SetResult(v string) {
	x.Result = v
}

type URLExpandResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Result string
}

func (b0 URLExpandResponse_builder) Build() *URLExpandResponse {
	m0 := &URLExpandResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Result = b.Result
	return m0
}

type UserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	URL           *[]*URLData            `protobuf:"bytes,1,rep,name=url,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURLsResponse) Reset() {
	*x = UserURLsResponse{}
	mi := &file_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLsResponse) ProtoMessage() {}

func (x *UserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserURLsResponse) GetUrl() []*URLData {
	if x != nil {
		if x.URL != nil {
			return *x.URL
		}
	}
	return nil
}

func (x *UserURLsResponse) SetUrl(v []*URLData) {
	x.URL = &v
}

type UserURLsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Url []*URLData
}

func (b0 UserURLsResponse_builder) Build() *UserURLsResponse {
	m0 := &UserURLsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.URL = &b.Url
	return m0
}

type URLData struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	ShortURL      string                 `protobuf:"bytes,1,opt,name=short_url,json=short_url,proto3"`
	OriginalURL   string                 `protobuf:"bytes,2,opt,name=original_url,json=original_url,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *URLData) GetShortURL() string {
	if x != nil {
		return x.ShortURL
	}
	return ""
}

func (x *URLData) GetOriginalURL() string {
	if x != nil {
		return x.OriginalURL
	}
	return ""
}

func (x *URLData) SetShortURL(v string) {
	x.ShortURL = v
}

func (x *URLData) SetOriginalURL(v string) {
	x.OriginalURL = v
}

type URLData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ShortURL    string
	OriginalURL string
}

func (b0 URLData_builder) Build() *URLData {
	m0 := &URLData{}
	b, x := &b0, m0
	_, _ = b, x
	x.ShortURL = b.ShortURL
	x.OriginalURL = b.OriginalURL
	return m0
}

var File_grpc_proto protoreflect.FileDescriptor

const file_grpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"grpc.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x11URLShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\",\n" +
	"\x12URLShortenResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\"\n" +
	"\x10URLExpandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x11URLExpandResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"3\n" +
	"\x10UserURLsResponse\x12\x1f\n" +
	"\x03url\x18\x01 \x03(\v2\r.grpc.URLDataR\x03url\"I\n" +
	"\aURLData\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl2\xd1\x01\n" +
	"\x10ShortenerService\x12?\n" +
	"\n" +
	"ShortenURL\x12\x17.grpc.URLShortenRequest\x1a\x18.grpc.URLShortenResponse\x12<\n" +
	"\tExpandURL\x12\x16.grpc.URLExpandRequest\x1a\x17.grpc.URLExpandResponse\x12>\n" +
	"\fListUserURLs\x12\x16.google.protobuf.Empty\x1a\x16.grpc.UserURLsResponseB\vZ\tgrpc/grpcb\x06proto3"

var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_proto_goTypes = []any{
	(*URLShortenRequest)(nil),  // 0: grpc.URLShortenRequest
	(*URLShortenResponse)(nil), // 1: grpc.URLShortenResponse
	(*URLExpandRequest)(nil),   // 2: grpc.URLExpandRequest
	(*URLExpandResponse)(nil),  // 3: grpc.URLExpandResponse
	(*UserURLsResponse)(nil),   // 4: grpc.UserURLsResponse
	(*URLData)(nil),            // 5: grpc.URLData
	(*empty.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_grpc_proto_depIDxs = []int32{
	5, // 0: grpc.UserURLsResponse.url:type_name -> grpc.URLData
	0, // 1: grpc.ShortenerService.ShortenURL:input_type -> grpc.URLShortenRequest
	2, // 2: grpc.ShortenerService.ExpandURL:input_type -> grpc.URLExpandRequest
	6, // 3: grpc.ShortenerService.ListUserURLs:input_type -> google.protobuf.Empty
	1, // 4: grpc.ShortenerService.ShortenURL:output_type -> grpc.URLShortenResponse
	3, // 5: grpc.ShortenerService.ExpandURL:output_type -> grpc.URLExpandResponse
	4, // 6: grpc.ShortenerService.ListUserURLs:output_type -> grpc.UserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIDxs,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIDxs = nil
}
